CREATE DATABASE MYMAP
USE MYMAP

CREATE TABLE VERTEX (
	ID INT PRIMARY KEY IDENTITY (0,1),
	X FLOAT,
	Y FLOAT,
	VERTEXNAME NVARCHAR(100) NOT NULL,
	NUMBER_VERTEX_KE INT DEFAULT 0  NOT NULL
) 

CREATE TABLE VERTEX_VERTEX( 
	V1 INT,
	V2 INT,
	WEIGHT FLOAT NOT NULL,
	PRIMARY KEY (V1,V2),
	CONSTRAINT FK_VERTEX_VERTEX_X1Y1 FOREIGN KEY (V1) REFERENCES VERTEX(ID),
	CONSTRAINT FK_VERTEX_VERTEX_X2Y2 FOREIGN KEY (V2) REFERENCES VERTEX(ID), 
)


CREATE TABLE VERTEX_SAVED (
	STT INT IDENTITY (1,1),
	ID INT NOT NULL,
	X FLOAT,
	Y FLOAT,
	VERTEXNAME NVARCHAR(100) NOT NULL,
	NUMBER_VERTEX_KE INT DEFAULT 0  NOT NULL,
	DATECHANGE DATETIME NOT NULL,
	PRIMARY KEY(STT,ID),
	CONSTRAINT FK_VERTEX_SAVED FOREIGN KEY (ID) REFERENCES VERTEX(ID), 
) 

CREATE TABLE MAPUSER(
	USERNAME VARCHAR(100) PRIMARY KEY,
	PASSWORD VARCHAR(100) NOT NULL
)


DELETE FROM VERTEX_VERTEX
DELETE FROM VERTEX
DROP TABLE VERTEX_VERTEX
DROP TABLE VERTEX