//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMap.Model
{
    using MyMap.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class VERTEX_VERTEX :BaseViewModel
    {
        private int _V1 { get; set; }
        public int V1 { get => _V1; set { _V1 = value; OnPropertyChanged(); } }

        private int _V2 { get; set; }
        public int V2 { get => _V2; set { _V2 = value; OnPropertyChanged(); } } 

        private double _WEIGHT { get; set; } 
        public double WEIGHT { get => _WEIGHT; set { _WEIGHT = value; OnPropertyChanged(); } }

        public virtual VERTEX VERTEX { get; set; }
        public virtual VERTEX VERTEX1 { get; set; }
    }
}
