//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMap.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYMAPEntities2 : DbContext
    {
        public MYMAPEntities2()
            : base("name=MYMAPEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MAPUSER> MAPUSERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VERTEX> Vertices { get; set; }
        public virtual DbSet<VERTEX_SAVED> VERTEX_SAVED { get; set; }
        public virtual DbSet<VERTEX_VERTEX> VERTEX_VERTEX { get; set; }
    }
}
