//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERTEX_SAVED
    {
        public int STT { get; set; }
        public int ID { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public string VERTEXNAME { get; set; }
        public int NUMBER_VERTEX_KE { get; set; }
        public System.DateTime DATECHANGE { get; set; }
    
        public virtual VERTEX VERTEX { get; set; }
    }
}
