//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMap.Model
{
    using MyMap.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class VERTEX : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VERTEX()
        {
            this.VERTEX_VERTEX = new HashSet<VERTEX_VERTEX>();
            this.VERTEX_VERTEX1 = new HashSet<VERTEX_VERTEX>();
            this.VERTEX_SAVED = new HashSet<VERTEX_SAVED>();
        }

        private int _ID { get; set; }
        public int ID { get => _ID; set { _ID = value; OnPropertyChanged(); } }

        private double _X { get; set; }
        public double X { get => _X; set { _X = value; OnPropertyChanged(); } }

        private double _Y { get; set; }
        public double Y { get => _Y; set { _Y = value; OnPropertyChanged(); } }

        private string _VERTEXNAME { get; set; }
        public string VERTEXNAME { get => _VERTEXNAME; set { _VERTEXNAME = value; OnPropertyChanged(); } }

        private int _NUMBER_VERTEX_KE { get; set; }
        public int NUMBER_VERTEX_KE { get => _NUMBER_VERTEX_KE; set { _NUMBER_VERTEX_KE = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERTEX_VERTEX> VERTEX_VERTEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERTEX_VERTEX> VERTEX_VERTEX1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERTEX_SAVED> VERTEX_SAVED { get; set; }
    }
}
